// Phosphor icon name mappings for all Lucide icons currently used
export const ICON_MAP = {
  // Navigation & UI
  X: "X",
  ChevronRight: "CaretRight",
  ChevronLeft: "CaretLeft",
  ChevronUp: "CaretUp",
  ChevronDown: "CaretDown",
  ChevronRightIcon: "CaretRight",
  ChevronDownIcon: "CaretDown",
  ChevronUpIcon: "CaretUp",
  Plus: "Plus",
  Minus: "Minus",
  Search: "MagnifyingGlass",
  Menu: "List",

  // Actions
  Trash2: "Trash",
  Edit: "Pencil",
  Copy: "Copy",
  Download: "Download",
  Upload: "Upload",
  Share: "ShareNetwork",
  Settings: "Gear",
  Refresh: "ArrowClockwise",
  Pencil: "Pencil",

  // Status
  CheckCircle2: "CheckCircle",
  CheckCircle: "CheckCircle",
  XCircle: "XCircle",
  AlertCircle: "WarningCircle",
  Info: "Info",
  ShieldAlert: "ShieldWarning",
  ShieldCheck: "ShieldCheck",
  ShieldWarning: "ShieldWarning",
  Shield: "Shield",
  CircleCheckIcon: "CheckCircle",
  InfoIcon: "Info",
  TriangleAlertIcon: "Warning",
  OctagonXIcon: "XCircle",
  Circle: "Circle",
  Warning: "Warning",

  // Media
  Volume2: "SpeakerHigh",
  Mic: "Microphone",
  MicOff: "MicrophoneSlash",
  Video: "Video",
  VideoOff: "VideoSlash",
  Camera: "Camera",
  Image: "Image",

  // Layout
  LayoutGrid: "GridFour",
  LayoutDashboard: "Layout",
  List: "List",
  Grid: "GridFour",
  ListChecks: "ListChecks",

  // User & Auth
  User: "User",
  Users: "Users",
  UserPlus: "UserPlus",
  UserCheck: "UserCheck",
  LogIn: "SignIn",
  LogOut: "SignOut",
  Mail: "Envelope",
  Lock: "Lock",
  Unlock: "LockOpen",
  Eye: "Eye",
  EyeOff: "EyeSlash",
  Fingerprint: "FingerprintSimple",
  Key: "Key",

  // Time & Calendar
  Calendar: "Calendar",
  Clock: "Clock",
  Timer: "Timer",

  // Data
  File: "File",
  FileText: "FileText",
  FileCheck2: "ClipboardText",
  Folder: "Folder",
  Database: "Database",
  Server: "Server",

  // Communication
  MessageSquare: "Chat",
  Send: "Send",
  Bell: "Bell",
  Flag: "Flag",
  Phone: "Phone",

  // Arrows & Navigation
  ArrowRight: "ArrowRight",
  ArrowLeft: "ArrowLeft",
  ArrowUp: "ArrowUp",
  ArrowDown: "ArrowDown",
  ExternalLink: "ArrowSquareOut",
  ArrowUpRight: "ArrowUpRight",
  ArrowDownRight: "ArrowDownRight",
  ArrowRightIcon: "ArrowRight",
  ArrowLeftIcon: "ArrowLeft",

  // Misc
  Home: "House",
  Briefcase: "Briefcase",
  BriefcaseBusiness: "Briefcase",
  Building: "Building",
  Building2: "Building",
  Globe: "Globe",
  Link: "Link",
  Link2: "LinkSimple",
  Tag: "Tag",
  Bookmark: "Bookmark",
  Star: "Star",
  Heart: "Heart",
  Layers: "Layers",
  Zap: "Lightning",
  Target: "Target",
  Filter: "Funnel",
  Sort: "ArrowsUpDown",
  Palette: "Palette",
  MapPin: "MapPin",
  SlidersHorizontal: "SlidersHorizontal",
  GripVertical: "DotsSixVertical",
  ZoomIn: "ZoomIn",
  AlertTriangle: "Warning",
  Pause: "Pause",
  Maximize: "WindowMaximize",
  Monitor: "Monitor",
  Check: "Check",
  Loader2: "Spinner",
  Loader2Icon: "Spinner",
  Square: "Square",
  XIcon: "X",
  CheckIcon: "Check",
  ScrollText: "FileText",
  TrendingUp: "TrendingUp",
  TrendingDown: "TrendingDown",
  Sparkles: "Sparkle",
  Quote: "Quote",
  PieChart: "ChartPieSlice",
  CheckSquare: "CheckSquare",
  Sun: "Sun",
  Moon: "Moon",
  PowerOff: "Power",
  Power: "Power",
  Handshake: "Handshake",
  Webhook: "Webhook",
  CreditCard: "CreditCard",
  ClipboardList: "ClipboardText",
  ChartBar: "Graph",
  DotsThree: "DotsThree",
  CaretLeft: "CaretLeft",
  CaretRight: "CaretRight",
  ArrowUpDown: "ArrowsUpDown",
} as const;

export type LucideIconName = keyof typeof ICON_MAP;
export type PhosphorIconName = typeof ICON_MAP[LucideIconName];